# Generated by Django 4.1.3 on 2023-04-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_spotifyaccesscode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyaccesscode',
            name='accessToken',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='spotifyaccesscode',
            name='refreshToken',
            field=models.CharField(max_length=200),
        ),
    ]
